### ISSUE TITLE
java8 local fun debug

### ISSUE THREAD

**Issue by caserzer** [aliyun/fun#103]
use example got
> FC Invoke Start RequestId: 3db83578-38ae-4eb1-9b70-17f3e30ba375
handle user request is example.App::handleRequest
cache is null!
2018-12-10 14:35:00.241 [ERROR] {
  "errorMessage" : "Cannot find the class example.App in your zip file and please make sure it is in the right path 'example/App'",
  "errorType" : "java.lang.ClassNotFoundException",
  "errorCause" : "example.App",
  "stackTrace" : [ "java.net.URLClassLoader.findClass(URLClassLoader.java:381)", "java.lang.ClassLoader.loadClass(ClassLoader.java:424)", "java.lang.ClassLoader.loadClass(ClassLoader.java:357)", "java.lang.Class.forName0(Native Method)", "java.lang.Class.forName(Class.java:348)" ]
}
{
  "errorMessage" : "Cannot find the class example.App in your zip file and please make sure it is in the right path 'example/App'",
  "errorType" : "java.lang.ClassNotFoundException",
  "errorCause" : "example.App",
  "stackTrace" : [ "java.net.URLClassLoader.findClass(URLClassLoader.java:381)", "java.lang.ClassLoader.loadClass(ClassLoader.java:424)", "java.lang.ClassLoader.loadClass(ClassLoader.java:ng.ClassLoader.loadClass(ClassLoader.java:357)", "java.lang.Class.forName0(Native Method)", "java.lang.Class.forName(Class.java:348)" ]
}FC Invoke End RequestId: 3db83578-38ae-4eb1-9b70-17f3e30ba375

RequestId: 3db83578-38ae-4eb1-9b70-17f3e30ba375          Billed Duration: 1849 ms        Memory Size: 1980 MB    Max Memory Used: 41 MB

PS D:\Aliyun\fun\examples\local> D:\Aliyun\fun-v2.7.0-win-x64.exe\fun local invoke -d 3000 java8
skip pulling image aliyunfc/runtime-java8:1.1.0...
> FC Invoke Start RequestId: fc2dd22b-d035-4bc0-9fa3-c18e908a455e
handle user request is example.App::handleRequest
cache is null!
2018-12-10 14:42:22.219 [ERROR] {
  "errorMessage" : "Cannot find the class example.App in your zip file and please make sure it is in the right path 'example/App'",
  "errorType" : "java.lang.ClassNotFoundException",
  "errorCause" : "example.App",
  "stackTrace" : [ "java.net.URLClassLoader.findClass(URLClassLoader.java:381)", "java.lang.ClassLoader.loadClass(ClassLoader.java:424)", "java.lang.ClassLoader.loadClass(ClassLoader.java:357)", "java.lang.Class.forName0(Native Method)", "java.lang.Class.forName(Class.java:348)" ]
}
{
  "errorMessage" : "Cannot find the class example.App in your zip file and please make sure it is in the right path 'example/App'",
  "errorType" : "java.lang.ClassNotFoundException",
  "errorCause" : "example.App",
  "stackTrace" : [ "java.net.URLClassLoader.findClass(URLClassLoader.java:381)", "java.lang.ClassLoader.loadClass(ClassLoader.java:424)", "java.lang.ClassLoader.loadClass(ClassLoader.java:357)", "java.lang.Class.forName0(Native Method)", "java.lang.Class.forName(Class.java:348)" ]
}FC Invoke End RequestId: fc2dd22b-d035-4bc0-9fa3-c18e908a455e

Env: windows 64 fun 2.7

**Comment by tanhe123** [comment]
fixed by #105

**Comment by qstevens** [comment]
seeing this issue again running in local

>skip pulling image aliyunfc/runtime-java8:1.9.21...
FC Invoke Start RequestId: 09db69bb-5533-471b-8769-f3fcb857e994
2022-05-17 03:44:05.140 [ERROR] {
  "errorMessage" : "Cannot find the class example.App in your zip file and please make sure it is in the right path 'example/App'",
  "errorType" : "java.lang.ClassNotFoundException",
  "errorCause" : "example.App",
  "stackTrace" : [ "java.net.URLClassLoader.findClass(URLClassLoader.java:381)", "java.lang.ClassLoader.loadClass(ClassLoader.java:424)", "java.lang.ClassLoader.loadClass(ClassLoader.java:357)", "java.lang.Class.forName0(Native Method)", "java.lang.Class.forName(Class.java:348)", "aliyun.serverless.runtime.util.AliFCUtil.loadUserFunctionInstance(AliFCUtil.java:121)", "aliyun.serverless.runtime.util.AliFCUtil.loadUserHandlerObject(AliFCUtil.java:86)" ]
}
FC Invoke End RequestId: 09db69bb-5533-471b-8769-f3fcb857e994
