### ISSUE TITLE
请允许设置API 网关的 入参请求模式

### ISSUE THREAD

**Issue by ijustyce** [aliyun/fun#11]
我们没必要把所有的入参都配置好，这是项可选的工作，配置了能自动生成文档，没配置请至少 允许我们使用 入参透传模式，而不是入参映射，目前我没找到类似的设置。我起初纳闷为什么我的参数被吃了，折腾了一会才发现是入参映射造成的，而且每次 deploy 都会重置为 入参映射。

是否有办法设置为入参透传，哪怕是临时的解决方案也行，不想自己去读代码并修改它、

**Comment by ijustyce** [comment]
我最终还是自己把它改了。打开 deploy.js  在 165行 之后添加：
`    
const len = requestParameters.length
let requestMode = "PASSTHROUGH"
if (len > 0) {
    requestMode = "MAPPING"
}
`
在198 行之后添加
`
'RequestMode': requestMode
`

**Comment by JacksonTian** [comment]
希望能提交 Pull Request 回来。
