### ISSUE TITLE
Event事件源是否支持指定Api gateway

### ISSUE THREAD

**Issue by zxkane** [aliyun/fun#110]
在[spec文档](https://github.com/aliyun/fun/blob/master/docs/specs/2018-04-03-zh-cn.md?spm=a2c4g.11186623.2.24.6aa428feFBC3Eu&file=2018-04-03-zh-cn.md#%E4%BA%8B%E4%BB%B6%E6%BA%90%E7%B1%BB%E5%9E%8B)中，事件源类型清单中并没有**Api**网关，也没有详细用法。

但在如下图的地方又说支持指定**Api**，

<img width="1170" alt="default" src="https://user-images.githubusercontent.com/843303/50082277-7f0e3e80-022b-11e9-8f5e-30b0c30aaa85.png">

是否Event支持指定Api网关？是的话，可否在事件源清单中补充上详细用法？

在实际使用中，我发现如果指定了Event是Http，即使定义了Api网关，网关转发请求的时候会报如下错误。

> exception:  http invoke FC error,requestId=9EE0020F-980D-4EB1-B5F4-2119CDC4CDE9,result={"ErrorCode":"InvalidArgument","ErrorMessage":"Function with http trigger(name: http-test) can only be invoked with http trigger URL"}java.lang.Exception

**Comment by tanhe123** [comment]
部署 api 网关，可以参考这里的示例：https://github.com/aliyun/fun/blob/master/docs/usage/getting_started-zh.md#%E7%A4%BA%E4%BE%8B

如果您已经配置了 http trigger，您需要先在控制台将该 http trigger 删掉。

**Comment by zxkane** [comment]
关于Event是否支持Api gateway，是否可以同时在Event下面添加触发器Api和HTTP？

**Comment by tanhe123** [comment]
Event 支持 Api Gateway。
不支持同时妹纸 Api 以及 HTTP trigger，因为他们入口函数的定义形式不同。

**Comment by zxkane** [comment]
谢谢解释
