### ISSUE TITLE
spec文档完善Api/tablestore详细配置说明

### ISSUE THREAD

**Issue by zxkane** [aliyun/fun#111]
[Api网关在spec文档](https://github.com/aliyun/fun/blob/master/docs/specs/2018-04-03-zh-cn.md#aliyunserverlessapi)过于简单，很多配置项没有列出，只能靠已有示例猜测。

另外function可以指定超时（比如10s），而gateway默认超时是3s，如果不能指定为比function超时配置更长的时间显然是不合理的。但是spec没有文档描述相关属性如何设置。

**Comment by tanhe123** [comment]
好的，文档我们会更新，您可以参考这个文档：https://help.aliyun.com/document_detail/43623.html?spm=a2c4g.11186623.6.624.26467432Fpi09V 。
spec 的规范基本上是与 api 网关的 api 一一对应的。

**Comment by zxkane** [comment]
> 好的，文档我们会更新，您可以先参考这个文档：https://help.aliyun.com/document_detail/43623.html?spm=a2c4g.11186623.6.624.26467432Fpi09V 。
> spec 规范基本上是与 api 网关的 api 一一对应的。

感谢文档链接！

文档预计什么时候可以更新？

目前希望通过spec指定Api网关的超时设置，这些写可以么？

```yaml          
x-aliyun-apigateway-service-config:
  service-timeout: 11000
```
另外为Api指定日志服务配置可以做到吗？在文档中貌似没有提到这块。

**Comment by zxkane** [comment]
@tanhe123 麻烦再请问下template中定义tablestore资源的时候，有关table的属性应该如何指定？

<img width="281" alt="default" src="https://user-images.githubusercontent.com/843303/50415420-d7f65c00-0855-11e9-89b9-eb6dbfbec879.png">

**Comment by tanhe123** [comment]
这几个值暂时没办法配置，建议您单独开个 issue，描述下您需要的字段，我们评估下。

**Comment by tanhe123** [comment]
api 网关使用文档：https://yq.aliyun.com/articles/689185
