### ISSUE TITLE
怎样在fun加library?

### ISSUE THREAD

**Issue by bbbbho** [aliyun/fun#127]
![screen shot 2019-01-07 at 9 42 49 pm](https://user-images.githubusercontent.com/11426354/50771948-131d7400-12c7-11e9-9ec5-25fe04995e2d.png)

**Comment by tanhe123** [comment]
看起来，您是 python 的函数。
请参考：https://www.alibabacloud.com/help/zh/doc-detail/56316.htm#adding-modules
