### ISSUE TITLE
增加 keyId 和 公钥的设置

### ISSUE THREAD

**Issue by aleelock** [aliyun/fun#14]
https://github.com/aliyun/fun/blob/22cce613ea1a7c21e1ba47bb306392496319dedf/lib/commands/deploy.js#L237

这个地方最好可以设置 keyId 和 公钥：
https://help.aliyun.com/document_detail/48295.html

不然每次用 fun deploy 之后，还要手动去添加 keyId 和公钥。

**Comment by JacksonTian** [comment]
收到您的需求，会在近期改进这个问题。

**Comment by tanhe123** [comment]
新版本也已经支持了该特性，会在月底发布

**Comment by tanhe123** [comment]
done.
