### ISSUE TITLE
fun-v2.10.1-win-x64 windows版本闪退

### ISSUE THREAD

**Issue by mysGitHub408** [aliyun/fun#149]
通过 releases 二进制压缩包解压获取到的程序，双击出现闪退现象，本地环境windows 10专业版，基于x64处理器，docker环境已安装完毕

**Comment by tanhe123** [comment]
您好，请按照教程中介绍的方法使用 Fun。当前支持 cmd 或者 powershell 等方式调用，不支持双击调用。
