### ISSUE TITLE
fun安装失败

### ISSUE THREAD

**Issue by mysGitHub408** [aliyun/fun#156]
您好，我本地环境是windows10 x86按照https://github.com/aliyun/fun/blob/master/docs/usage/installation-zh.md?spm=a2c4g.11186623.2.19.1fac28feU7UqR1&file=installation-zh.md 这里面的步骤：直接下载 Fun 二进制运行程序  对应版本号2.10.1，启动fun local invoke -h 命令     报 'fun' 不是内部或外部命令，也不是可运行的程序或批处理文件。请问我这边需要怎么处理？

**Comment by tanhe123** [comment]
如果您下载的文件是 fun-v2.10.2-win-x86.exe.zip，解压后，会有一个名为 fun-v2.10.2-win-x86.exe 的文件。

然后，在  fun-v2.10.2-win-x86.exe 所在的目录执行 `fun-v2.10.2-win-x86 local invoke -h` 即可。

**Comment by mysGitHub408** [comment]
好的，我本地使用java环境 如果做debug调试的时候，在fun中配置的yml文件内容中的codeuri是否可以配置为相对路径？

**Comment by tanhe123** [comment]
可以的，相对路径，绝对路径都支持，但是要指定为打包后的 jar
