### ISSUE TITLE
fun-local java环境 本地调试错误

### ISSUE THREAD

**Issue by mysGitHub408** [aliyun/fun#157]
您好：我在我本机（windows）进行fun-local java 环境的debug调试，出现以下问题，一直报链接超时，
![image](https://user-images.githubusercontent.com/47553776/53386766-8a65af00-39be-11e9-9d6a-1239260898ab.png)
然后，idea 里面配置的remote 端口是3000，启动debug报Unable to open debugger port (localhost:3000): java.net.ConnectException "Connection refused: connect

**Comment by tanhe123** [comment]
看起来是在 pull 镜像的时候出了问题，可以手动执行试一下：

```
docker pull aliyunfc/runtime-java8:1.4.0
```

解决方案可以使用阿里云或者其他平台的镜像加速器服务：

https://yq.aliyun.com/articles/29941
