### ISSUE TITLE
[疑问]关于触发器

### ISSUE THREAD

**Issue by duncup** [aliyun/fun#171]
修改 yml 文件并移除某HTTP触发器后部署，线上的触发器并没有移除。

**Comment by tanhe123** [comment]
现在的处理措施是当线上的触发器配置与本地不一致时，会提示警告：
https://github.com/aliyun/fun/pull/196
https://github.com/aliyun/fun/pull/197

**Comment by tanhe123** [comment]
目前只能手动通过控制删除这些触发器。

如果没有解决问题，可以再提个 issue，我们重新评估下。这个 issue 先 close 了。
