### ISSUE TITLE
Http Trigger 本地运行调试:  ----错误

### ISSUE THREAD

**Issue by guoyon** [aliyun/fun#183]
C:\Users\guoyon\javafc>fun local start
http trigger http-test of local-http-demo/nodejs8 was registered
        url: http://localhost:8000/2016-08-15/proxy/local-http-demo/nodejs8/
        methods: [ 'GET', 'POST', 'PUT' ]
        authType: ANONYMOUS

function compute app listening on port 8000!

skip pulling image aliyunfc/runtime-nodejs8:1.5.0...
/var/fc/runtime/nodejs8/mock.sh exited with code null
FC Invoke Start RequestId: f312c8df-0083-4540-bf0b-1c3312f7a26e
load code for handler:index.initializer
2019-04-11T07:39:21.073Z f312c8df-0083-4540-bf0b-1c3312f7a26e [verbose] initializer invoked
FC Invoke End RequestId: f312c8df-0083-4540-bf0b-1c3312f7a26e
FC Invoke Start RequestId: f312c8df-0083-4540-bf0b-1c3312f7a26e
load code for handler:index.handler
FC Invoke End RequestId: f312c8df-0083-4540-bf0b-1c3312f7a26e

**Comment by guoyon** [comment]
/var/fc/runtime/nodejs8/mock.sh exited with code null

**Comment by guoyon** [comment]
url: http://localhost:8000/2016-08-15/proxy/local-http-demo/nodejs8/
返回 
{"errorMessage":"Process exited unexpectedly before completing request"}

**Comment by tanhe123** [comment]
更新最新版本，这个问题应该已经 fix 了

**Comment by guoyon** [comment]
谢谢

**Comment by guoyon** [comment]
你说的是fun 的版本吗？

**Comment by tanhe123** [comment]
fun 的最新版本 2.11.2 修复了这个问题，请试一下

**Comment by guoyon** [comment]
更新过了 
+ @alicloud/fun@2.11.2
updated 108 packages in 68.659s

C:\Users\guoyon\javafc>fun local start
http trigger http-test of local-http-demo/nodejs6 was registered
        url: http://localhost:8000/2016-08-15/proxy/local-http-demo/nodejs6/
        methods: [ 'GET', 'POST', 'PUT' ]
        authType: ANONYMOUS


function compute app listening on port 8000!

1.5.2: Pulling from aliyunfc/runtime-nodejs6
3d77ce4481b1: Already exists
7d2f32934963: Already exists
0c5cf711b890: Already exists
1.5.2: Pulling from aliyunfc/runtime-nodejs6
3d77ce4481b1: Already exists
7d2f32934963: Already exists
0c5cf711b890: Already exists
9593dc852d6b: Already exists
4e3b8a1eb914: Already exists
ddcf13cc1951: Already exists
2e460d114172: Already exists
d94b1226fbf2: Already exists
1c998d4e237d: Waiting
4804ca5a5fa6: Waiting
dd40dcb9e7f7: Waiting
a9805595237d: Waiting
07d1857cdee7: Waiting
049029d97a2b: Waiting
f1febb506691: Waiting
81117cefad49: Waiting
576af9b0cae1: Waiting
81c7f8df7d79: Waiting
e88fff8a131d: Waiting
c7ba11a0dded: Waiting
(node:10852) UnhandledPromiseRejectionWarning: context canceled
(node:10852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by guoyon** [comment]
卡着不动了 。 以前的docker镜像需要删除吗？

**Comment by tanhe123** [comment]
卡住是正常的，网络问题，建议配置下 docker 源，pull 会快些。

另外，也可以手动执行 `docker pull aliyunfc/runtime-nodejs6:1.5.2` pull 镜像

**Comment by guoyon** [comment]
谢谢
