### ISSUE TITLE
希望可以在 faas.yml 中把API网关设置为 PRIVATE

### ISSUE THREAD

**Issue by fushang318** [aliyun/fun#2]
希望可以在 faas.yml 中把API网关设置为 PRIVATE，看代码目前是写死的
https://github.com/aliyun/fun/blob/5b3f14a62273c7ce30b2dc6c56a02141b8a01f77/lib/commands/deploy.js#L192

**Comment by JacksonTian** [comment]
请升级到 1.4.0
