### ISSUE TITLE
配置了错误的 accountId 时，需要更友好的错误提示

### ISSUE THREAD

**Issue by tanhe123** [aliyun/fun#201]
现在有些用户并不知道 accountid 是什么，可能会配置 accountid 为以下几种情况：

1. 配置成登陆用户名，这种情况下会抛出 `getaddrinfo ENOTFOUND` 类型的异常，原因是无法解析到正确的域名。
2. 配置成子用户 accountid，对于这种情况，会提示  `message: The service or function doesn't belong to you..`

最好，在工具层面就将这个问题检测出来。

**Comment by abersheeran** [comment]
建议把 accountid 是根账号ID这个事写进文档里。我是找到你这个 issue 才知道我id填成了子用户的id

**Comment by tanhe123** [comment]
命令行提示错误信息，您觉得表达的不够清晰吗？

**Comment by abersheeran** [comment]
@tanhe123 错误信息表达的很清楚，但是我似乎没有在任何地方（除了这）能知道错误信息对应的解决方案是什么。当我查了数个文档之后，我终于从Google 进了这个 Github issue，但似乎并不是所有人都能上Google。
所以我认为，你们应该把这个常见错误写进文档里。
