### ISSUE TITLE
安装依赖永远无法自动停止

### ISSUE THREAD

**Issue by l616769490** [aliyun/fun#260]
fun install --save --runtime python3 --package-type pip PyMySQL
skip pulling image aliyunfc/runtime-python3.6:build-1.5.3...
Task => [UNNAMED]
     => PYTHONUSERBASE=/code/.fun/python pip install --user PyMySQL

然后就会一直停在这里（我等了两个多小时），尝试安装了好多依赖都是这样的。可以强行通过ctrl+c能够停止，并且依赖能用。但是由于不是正常停止，始终还是不放心。希望能解决一下这个问题。

**Comment by tanhe123** [comment]
请告知您的系统以及 fun 版本。

您也可以使用 `fun -vvvv install --save --runtime python3 --package-type pip PyMySQL` 看下更详细的日志

**Comment by l616769490** [comment]
> 请告知您的系统以及fun版本。
> 
> 也。您可以使用`fun -vvvv install --save --runtime python3 --package-type pip PyMySQL`看下更详细的日志

你好，系统是win10，fun版本：2.15.0，使用的终端为powershell

**Comment by tanhe123** [comment]
已经重现问题，会尽快 fix

**Comment by Booooooger** [comment]
出现同样的问题。

fun version: 2.15.0
system info : Windows 10 Pro 1903 build 18362
terminal: powershell
