### ISSUE TITLE
希望可以在 faas.yml 中可以设置API网关的认证方式

### ISSUE THREAD

**Issue by fushang318** [aliyun/fun#3]
希望可以在 faas.yml 中可以设置API网关的认证方式，
1. 比如设置为  OpenID Connect
2. 并设置 OpenID Connect下的两种类型（认证API，业务API）
3. 设置 OpenID Connect模式 下的 token

https://github.com/aliyun/fun/blob/5b3f14a62273c7ce30b2dc6c56a02141b8a01f77/lib/commands/deploy.js#L193

**Comment by JacksonTian** [comment]
请升级到 1.4.0。支持 OpenIDConnect的 业务API 。

https://github.com/aliyun/fun/tree/master/examples/openid_connect 示例。

**Comment by JacksonTian** [comment]
@fushang318 issue 我先关闭了，如果有任何问题，请 reopen。
