### ISSUE TITLE
希望增加一个在 faas.yml 中给API网关设置了请求入参信息，后端服务参数，常量参数，自定义系统参数等信息的示例

### ISSUE THREAD

**Issue by fushang318** [aliyun/fun#4]
希望增加一个在 faas.yml 中给API网关设置了请求入参信息，后端服务参数，常量参数，自定义系统参数等信息的示例

看现在应该是支持的，但是不知道具体格式是啥

https://github.com/aliyun/fun/blob/5b3f14a62273c7ce30b2dc6c56a02141b8a01f77/lib/commands/deploy.js#L201-L204

**Comment by jinchun** [comment]
没人维护吗？

**Comment by JacksonTian** [comment]
@jinchun 有人维护。

**Comment by jinchun** [comment]
@JacksonTian 这个 issue 没官方回复呢？我也好奇这个 yml 配置。

**Comment by JacksonTian** [comment]
我们推荐尽量是透传。

**Comment by tanhe123** [comment]
文档可以参考：https://yq.aliyun.com/articles/689185
