### ISSUE TITLE
faas.yml 目前还不支持添加日志服务权限吗？

### ISSUE THREAD

**Issue by try-life** [aliyun/fun#40]
https://github.com/aliyun/fun/blob/5b3f14a62273c7ce30b2dc6c56a02141b8a01f77/lib/commands/deploy.js#L98-L150

看了下代码，涉及到 ram 的就这一段，看起来像是只为 `api gateway`固定写的。

另外问一下，https://github.com/aliyun/serverless-aliyun-function-compute 这个是另外一个组在维护吗？这个也尝试过，和 fun 功能上有交集，但内容更丰富些，当然也有很多地方不完善的。。头疼

**Comment by JacksonTian** [comment]
有疑问的地方可以提需求

**Comment by try-life** [comment]
faas.yml 里希望可以添加如下配置：

1. 日志服务授权
2. api-gateway 签名密钥配置

如果有，如果能提供更详细的文档更好。
fun 这个名字我想取的时候是有`have fun`的意思在内的。
现在文档方面不够完善，基本靠读源码和看各种官方例子（量少）来配置。。

**Comment by tanhe123** [comment]
您好，在 6 月底，我们会发布一个版本，支持日志服务创建、以及授权。
api-gateway 签名密钥配置这个需求我们会评估下。

**Comment by JacksonTian** [comment]
暂时我们在v1 这个版本上也添加下 log 的配置。预计下周可用。

**Comment by try-life** [comment]
@tanhe123 @JacksonTian 感谢两位回复。
另外：
 - faas.yaml 文件里支持变量吗？
 - faas.yaml functions 里能加一个环境变量的支持吗？

**Comment by tanhe123** [comment]
1. faas.yaml 文件里支持变量吗？
     这个暂时还不支持
2. faas.yaml functions 里能加一个环境变量的支持吗？
    新的版本已经支持了
3. api-gateway 签名密钥配置
    新的版本已经支持了

月底会发布新版本，请耐心等待新版本发布。

**Comment by try-life** [comment]
多谢！

**Comment by tanhe123** [comment]
2.0.1 已经发布了
