### ISSUE TITLE
请问最新版是1.6.3吗？无法运行fun config和fun deploy

### ISSUE THREAD

**Issue by senseluo** [aliyun/fun#47]
最新的文档中没有提及faas.yml，只有template.yml
所以没有搞懂是文档没更新还是代码没更新~~

```
$ fun deploy
Current folder not a Faas project
The folder must contains faas.yml or faas.yaml
```

**Comment by vangie** [comment]
我们正在 release 新版本，新版本还没有进入 npm 库。

**Comment by senseluo** [comment]
@vangie 好的 等等 谢谢~

**Comment by senseluo** [comment]
@vangie 能够以后发布新版本加个类似CHANGELOG的说明吗

**Comment by vangie** [comment]
> @vangie 以后发布新版本能否加个类似CHANGELOG的说明吗

很好的建议，今后新版的维护我们会加上这个说明文件。

**Comment by jinchun** [comment]
看最新的 commit和最新的文档说明，以后是都用 template.yml，放弃使用 faas.yaml 了是吗？

**Comment by tanhe123** [comment]
2.0.1 已经发布了
