### ISSUE TITLE
运行脚本不能成功创建函数计算服务

### ISSUE THREAD

**Issue by Kovvi** [aliyun/fun#70]
当我是一个新用户时，运行脚本不能成功创建函数计算服务，显示“Account is inactive to this service”错误的信息。但是输入的账号ID、Access Key Id、Access Key Secret都是正确的。
![image](https://user-images.githubusercontent.com/32712288/43874419-67c9125a-9bbe-11e8-8ad6-ee8d7747ba16.png)
脚本如下：
`ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  ygwww1-fc-local:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: 'youngget'
      LogConfig:
        Project: ygwww1-log
        Logstore: ygwww1-logstore-local
    ygwww1-fc-local:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs8
        MemorySize: 128
        CodeUri: './dist/target.zip'
        Timeout: 10`

**Comment by tanhe123** [comment]
很遗憾，如果您是新用户，只能通过手动去控制台开通该服务。
