### ISSUE TITLE
Can't deploy function

### ISSUE THREAD

**Issue by karudo** [aliyun/fun#86]
Trying to deploy function, but have error. What can be problem?

-> fun deploy
using region: ap-southeast-1
using accountId: *****
using accessKeyId: *****
using timeout: 15

Waiting for service video-transcoding-wrapper to be deployed...
FCAccessDeniedError: GET /services/video-transcoding-wrapper failed with 403. requestid: c39a5ca9-c896-ac44-fe6a-230ab01bfc87, message: The service or function doesn't belong to you..
    at Client.request (/Users/*****/aliyun-nodejs/node_modules/@alicloud/fc2/lib/client.js:156:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by tanhe123** [comment]
Check your accountId. The accountId must match your ak.

**Comment by sherryt400** [comment]
with `fcli` i am getting this error
```
Error: {
  "HttpStatus": 403,
  "RequestId": "391285b8-5f63-52b4-1f18-bf1c939917fe",
  "ErrorCode": "AccessDenied",
  "ErrorMessage": "The service or function doesn't belong to you."
}
```

and for `fun deploy` i get this
![screenshot from 2018-11-21 11-50-19](https://user-images.githubusercontent.com/13458688/48829112-4c3f6a80-ed93-11e8-9ebf-e5619253a867.png)

**Comment by sherryt400** [comment]
ok i have updated `account ID` now `fcli` is working fine, but still `fun deploy` is not working

**Comment by tanhe123** [comment]
It seems that your network has some problems.

You can test it by `ping ram.aliyuncs.com`.

**Comment by tanhe123** [comment]
@sherryt400 It will come soon.

Duplicated: https://github.com/aliyun/fun/issues/87.

**Comment by tanhe123** [comment]
[2.7.0](https://github.com/aliyun/fun/releases/tag/v2.7.0) released.
