### ISSUE TITLE
当使用CodeUri指定代码目录的时候，能否排除一些文件/文件夹

### ISSUE THREAD

**Issue by zsimple** [aliyun/fun#87]
开发的时候会有一些本地运行相关的文件，不希望打包上传，能否指定规则排除呢？

**Comment by zone1511** [comment]
能否支持類似以gitignore 的方式 告訴打包工具那些檔案 不需上傳

**Comment by tanhe123** [comment]
开发中了，请耐心等待

**Comment by tanhe123** [comment]
https://github.com/aliyun/fun/pull/100

**Comment by tanhe123** [comment]
[2.7.0](https://github.com/aliyun/fun/releases/tag/v2.7.0) released.
