### ISSUE TITLE
fun local invoke支持HTTP触发器调试

### ISSUE THREAD

**Issue by iFwu** [aliyun/fun#97]
使用 fun local invoke 时，无法对 HTTP 触发器进行调试

**Comment by tanhe123** [comment]
您好，http trigger 以及 api gateway 的本地调试都已经在开发了，敬请期待。

**Comment by tanhe123** [comment]
目前仅支持事件触发，您使用过程中有任何问题或者建议，可以反馈给我们

**Comment by tanhe123** [comment]
2.8.0 已支持：https://github.com/aliyun/fun/releases/tag/v2.8.0
